# Generated by Django 3.2.7 on 2022-01-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app06', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
