# Generated by Django 3.2.7 on 2021-12-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='isuser',
            field=models.BooleanField(default='True', verbose_name='用户是否被删除 1:未删除 0:删除'),
        ),
    ]
