# Generated by Django 3.2.7 on 2021-12-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_userinfo_isuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='isuser',
            new_name='is_delete',
        ),
    ]
