# Generated by Django 3.2.7 on 2021-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0002_author_authordetail_book_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, verbose_name='书名1'),
        ),
    ]
