# Generated by Django 3.2.7 on 2021-11-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0003_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, verbose_name='书名'),
        ),
    ]
