# Generated by Django 3.2.7 on 2021-11-29 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0004_alter_book_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
