# Generated by Django 3.2.7 on 2021-11-29 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0008_auto_20211129_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
