# Generated by Django 3.2.7 on 2021-12-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0010_auto_20211129_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_inventory',
            field=models.IntegerField(default=300, verbose_name='库存书籍'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_sold',
            field=models.IntegerField(default=1000, verbose_name='售出书籍'),
        ),
    ]
