# Generated by Django 3.2.7 on 2021-12-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0011_auto_20211201_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '其他')], verbose_name='性别')),
            ],
        ),
    ]
