# Generated by Django 3.2.7 on 2021-12-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app03', '0012_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='score',
            field=models.CharField(choices=[('A', '优秀'), ('B', '良好'), ('C', '及格'), ('D', '不及格')], max_length=32, null=True, verbose_name='成绩等级'),
        ),
    ]
